### ISSUE TITLE
Magento 2.4.6 setup di compilation is failing

### ISSUE THREAD

**Issue by eugene-petrov** [datafeedwatch/connector#10]
Step to reproduce:
run the command:
bin/magento set:di:com

Actual result:

Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 193.0 MiB
Fatal error: Type of DataFeedWatch\Connector\Plugin\QtyAndStock::$storeManager must be Magento\Store\Model\StoreManagerInterface (as in class DataFeedWatch\Connector\Plugin\Quantity) in /var/www/html/vendor/datafeedwatch/connector/Plugin/QtyAndStock.php on line 29

Expected result:

Compilation was started.
Plugin list generation... 9/9 [============================] 100% 1 min 995.5 MiB
Generated code and dependency injection configuration successfully.

**Comment by eugene-petrov** [comment]
Here is a possible fix: https://github.com/datafeedwatch/connector/pull/11

The reason that the child 
```php
    /**
     * @var StoreManagerInterface
     */
    protected $storeManager
```

and the parent

```php
    /**
     * @var StoreManagerInterface
     */
    protected StoreManagerInterface $storeManager
```
have different declarations for not the same property.

As the property is set as protected it can be removed from the child without any issues.

**Comment by wmwnuk** [comment]
Pull request tested and merged.
