### ISSUE TITLE
Magento 2.4.4 - php8.1 support

### ISSUE THREAD

**Issue by WebKenth** [datafeedwatch/connector#5]
Latests tag:

```json
    "require": {
        "php": "7.*"
    },
```

Magento 2.4.4 up's php compatability to php 8.1

please update your codebase and requirements <3

**Comment by pprmn** [comment]
Done in tag 3.1.1

**Comment by mortenbirkelund** [comment]
@wmwnuk Also interested in knowing if the module is compatible with 2.4.5?

**Comment by wmwnuk** [comment]
Module was tested on 2.4.5 and with php 8.1, also new tag / version was pushed to the repo.
