### ISSUE TITLE
Create a tag 3.1.2 from master and packagist

### ISSUE THREAD

**Issue by pprmn** [datafeedwatch/connector#6]
Hello

Can you create a 3.1.2 tag and push it on packagist so that we can have php 8.1 compatibility ?

Regards

Sébastien

**Comment by lsv** [comment]
@wmwnuk Please tag it - so its usuable.

**Comment by mortenbirkelund** [comment]
@wmwnuk Any news regarding this one?

**Comment by mortenbirkelund** [comment]
@wmwnuk any news regarding the missing tag?

**Comment by wmwnuk** [comment]
New tag/version was pushed.
