### ISSUE TITLE
Magento 2.4.4 - Allow oauth access

### ISSUE THREAD

**Issue by lsv** [datafeedwatch/connector#7]
If anybody got a "401 - Unauthorized" - on a Magento 2.4.4 or above - Magento 2.4.4 has a new setting that needs to be enabled, before datafeedwatch can read anything from your shop directly.

This undocumented by any datafeedwatch documentations.

Go to `Stores > Configuration > Services > OAuth > Consumer Settings > Allow OAuth Access Tokens to be used as standalone Bearer tokens`

Its not really recommended to enable this, but as of now - it needs to be enabled.

https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/

**Comment by wpsamurai** [comment]
@lsv thank you for sharing. Our help pages were updated with that workaround sometime ago. Also we have a task in our roadmap to add support for oAuth.
